CREATE TABLE IF NOT EXISTS sensor_readings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    node INTEGER NOT NULL,
    packet INTEGER NOT NULL,
    light INTEGER,
    temperature REAL,
    humidity REAL
);